### ISSUE TITLE
Implement CI/CD Pipeline for Automated Quality Checks

### ISSUE THREAD

**Issue by phuongwd** [phuongwd/nestjs-starter-template#2]
### Implement CI/CD Pipeline for Automated Quality Checks

* **Description:**
  Add a CI pipeline using GitHub Actions to automatically run linting, unit tests, and build validation on every pull request and push to main branches. This ensures ongoing code quality and prevents regressions.

* **Acceptance Criteria:**

  * Create `.github/workflows/ci.yml` for the pipeline configuration.
  * Steps should include:

    * Install dependencies (`npm ci`).
    * Run lint checks (`npm run lint`).
    * Run unit and e2e tests (`npm run test` and `npm run test:e2e`).
    * Validate build (`npm run build`).
  * Ensure pipeline runs on `pull_request` and `push` events for `main` and `develop` branches.
  * Add status badge to `README.md` indicating build status.
  * All steps should pass successfully before merging changes.

* **Priority:** High

---
Here’s a starter GitHub Actions workflow file you can place at `.github/workflows/ci.yml`:

```yaml
name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🎨 Run Lint Checks
        run: npm run lint

      - name: 🧪 Run Unit Tests
        run: npm run test -- --coverage

      - name: 🚀 Run E2E Tests
        run: npm run test:e2e

      - name: 📦 Build Application
        run: npm run build

      - name: ✅ Complete
        run: echo "CI pipeline finished successfully!"
```

### Notes:

* Adjust `node-version` if you’re using a different version in production.
* If your e2e tests require services like PostgreSQL or Redis, you can add Docker services under `services:` in the job.
* To add the build status badge to your `README.md`, include the following Markdown snippet:

```md
![CI](https://github.com/<YOUR_ORG>/<REPO_NAME>/actions/workflows/ci.yml/badge.svg)
```

Replace `<YOUR_ORG>` and `<REPO_NAME>` accordingly.
